### ISSUE TITLE
flextile.c missing

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-vanitygaps#1]
can't build with config.def.h cuz flextile.c is missing from the repo, I tried patching it with the flextile patch but it doesn't allow me as it says its been already patched ... there is also missing text in in config.def.h line 10
static       int smartgaps               = 0;   /* 1 means no outer gap when there is only one window */

the word const is missing between static and int

**Comment by bakkeby** [comment]
You are right, it was actually just a matter of deleting the line that tries to include flextile.c (it's integrated in vanitygaps.c).

The missing const was a leftover as I previously had keyboard shortcuts to toggle smartgaps on and off, but I removed that at some point.

I committed a change for both. Admittedly I haven't maintained this for a while as I have been more focused on the flexipatch build.
