### ISSUE TITLE
update vanitygaps layouts :D

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-vanitygaps#10]
I just realized that the vanitygaps diffs here don't include the fixes to the centered master, tile layout, and other layouts that we worked out over the last few weeks in the flexipatch repository :)

**Comment by bakkeby** [comment]
Yes had quite a bit more work to do sanity check every one of those layouts to bring them all up to the same standard.

The new locations are:
https://github.com/bakkeby/patches/blob/master/dwm/dwm-vanitygaps-6.2.diff
https://github.com/bakkeby/patches/blob/master/dwm/dwm-cfacts-vanitygaps-6.2.diff
