### ISSUE TITLE
Floating Centered Master broken

### ISSUE THREAD

**Issue by Schueni1** [bakkeby/dwm-vanitygaps#11]
I just tested the cfacts version on suckless.org.

Centered-floating-master seems to be broken. The floating master clients are not centered.

**Comment by bakkeby** [comment]
OK, can you clarify what you mean. If they are not centered where do they end up displaying and how do you replicate this?

**Comment by Schueni1** [comment]
They are only centered along the x axis, but at x-axis 0.
I patched it on top of a clean dwm-6.2 without any other patches.

**Comment by bakkeby** [comment]
I tried this but I couldn't replicate it.

**Comment by bakkeby** [comment]
@Schueni1 I am going to archive this old version of dwm, if you want to follow up on this then let's move the discussion over to https://github.com/bakkeby/patches
