### ISSUE TITLE
systray goes missing

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-vanitygaps#4]
the systray goes missing when I refresh my dwm or at random times, and wont come back until i completely kill and start dwm again

**Comment by kronikpillow** [comment]
ok, figgured it out when, when I mod+shift+q (quit) dwm eg restart it in a loop, systray stops working :)

sorry If Im bothering you, but a big fan of your patches, I'm testing them all one by one, and I'll continue reporting any bugs I find

**Comment by bakkeby** [comment]
Sorry, I meant to reply on this one - just busy with so many things. I have come across issues like this myself, typically when doing a lot of restarts as you have found.

I have also experienced dwm simply crashing when the first systray application starts. I don't have a way to replicate this consistently so not entirely sure how to debug this properly.

You say that the systray goes missing - do you have only one systray application? What I find is that sometimes the very first systray icon disappears (after many hours) while the other remain. The menu is still accessible if I right click all the way in the corner though, like it's 0 pixels or something. Stopping and starting the application restores the systray icon for me. This as well I am unable to replicate so not sure what to make of it. I would also be keen on working out why this happens.

I have always assumed that these issues are also present on the original [systray](https://dwm.suckless.org/patches/systray/) patch on the suckless website. I have never spent enough time with that to confirm though.

Incidentally the description was recently updated ref.
https://git.suckless.org/sites/commit/8b276d224d55cbbe8fed0f6e15bbe8dbf8ecd8d9.html

with the text

> _In case icons disappear when toggling the bar, try a different font size in dwm. This has helped at least in one case with pidgin._

So might be worth trying that.

**Comment by kronikpillow** [comment]
yes currently I have only 1 systray icon, Discord to be exact, I will try the font thing and report back ... 

to note, I personally know very little C, a beginner here, so I am unable to properly debug things, I'm just able to test things out and report issues :) I found that working with your patches makes my life much easier then having to manually patch everything I want to patch on my dwm build as your patches are updated :)

stopping and starting the application again doesn't restore the systray for me, and it goes missing only after I quit dwm (restart it in a loop with mod + shift + q) ... when I killall dwm manually, and then relogin to my desktop, the systray comes back ....

and no I don't think it's the font, as I'v changed the font from 10 to 12 and the problem persists

**Comment by kronikpillow** [comment]
I have also tried the dwm-flexipatch build, but the config is to confusing for me

**Comment by kronikpillow** [comment]
em no I don't think it's the font, my fontsize is 10, switched to 12 and still the same
