### ISSUE TITLE
pertag-configurable

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-vanitygaps#5]
with the pertag-configurable patch when you switch tags or basically do anything with windows, the bar keeps flickering like it's constantly refreshing ...

**Comment by bakkeby** [comment]
I wasn't able to replicate this with the pertag-configurable patch on top of a bare 6.2 dwm. I tried all the combinations of topbar, pertag and pertagbar that I could think of.

It's likely something else. Are you able to replicate this, and if so what configuration and additional patches do you have applied?

**Comment by kronikpillow** [comment]
sorry I forgot to reply to this because I started using flexipatch :D I will get back to you on this asap

**Comment by bakkeby** [comment]
I'll mark this as closed, but do let me know if you still have issues with this.
