### ISSUE TITLE
Dwm-hide_vacant_tags -6.2.diff cannot work on this project

### ISSUE THREAD

**Issue by ghost** [bakkeby/dwm-vanitygaps#8]
Dwm-hide_vacant_tags -6.2.diff cannot work on this project

https://dwm.suckless.org/patches/hide_vacant_tags/dwm-hide_vacant_tags-6.2.diff

**Comment by bakkeby** [comment]
Hi @NinjaMoon,

yes I wouldn't expect that to work out of the box, you'd need to patch manually if need be.

If you want that then I'd recommend having a look at [dwm-flexipatch](https://github.com/bakkeby/dwm-flexipatch) instead. It's perhaps overwhelming at first, but it has the majority of patches available.

\
Thanks,

-Stein
